/*
Problem

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

xn = xn-1 + xn-2.
*/

#include <iostream>
using namespace std;

int is_even(int number) 
{
    if(number % 2 == 0) 
    {
        return true;
    }
    return 0;
}

int main() {
    unsigned int next = 0 ;
    int sum = 0, first = 0;
    int second = 1;

    while(next <= 4000000) {
        next = first + second;
        first = second;
        second = next;

        if(is_even(next) == true) {
            sum += next;
        }
    }
    cout << sum << endl;
    return 0;
}
